// Assemble the static web surface served by Vercel's CDN from /public:
//   /                  → public/index.html         (landing page, committed)
//   /dashboard/        → public/dashboard/*         (operator SPA, generated here)
//
// The operator SPA references its assets at absolute /app.js and /styles.css, so
// to host it under /dashboard/ we copy it and rewrite those two paths. Its API
// calls (/api/*) are already absolute and hit the function unchanged.
import { mkdir, readFile, writeFile, copyFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = join(ROOT, 'src', 'operator', 'public')
const OUT = join(ROOT, 'public', 'dashboard')

await mkdir(OUT, { recursive: true })

// The landing page (public/index.html) is served by the Hono function at `/`
// (Vercel routes `/` to the function under the Hono preset, so static CDN
// serving of public/index.html doesn't win there). Emit it as a TS module the
// function imports — JSON.stringify keeps it escape-proof for any HTML content.
const landingHtml = await readFile(join(ROOT, 'public', 'index.html'), 'utf8')
await writeFile(
  join(ROOT, 'landing.generated.ts'),
  `// AUTO-GENERATED by scripts/build-web.mjs — do not edit. Source: public/index.html\nexport const LANDING_HTML = ${JSON.stringify(landingHtml)}\n`,
)

// The manifesto page (public/manifesto.html) is served the same way at
// /manifesto — emitted as a TS module the function imports.
const manifestoHtml = await readFile(join(ROOT, 'public', 'manifesto.html'), 'utf8')
await writeFile(
  join(ROOT, 'manifesto.generated.ts'),
  `// AUTO-GENERATED by scripts/build-web.mjs — do not edit. Source: public/manifesto.html\nexport const MANIFESTO_HTML = ${JSON.stringify(manifestoHtml)}\n`,
)

// Assets verbatim — app.js fetches /api/* (absolute), correct from any path.
await copyFile(join(SRC, 'app.js'), join(OUT, 'app.js'))
await copyFile(join(SRC, 'styles.css'), join(OUT, 'styles.css'))

// Chat portal → the serverless function. app.ts mounts it at /portal via a
// runtime import of examples/chat-portal/server.mjs; Vercel's esbuild leaves
// dynamic imports as runtime resolves and does NOT trace the portal's file
// reads (server.mjs reads public/* and .data/* relative to itself). So copy
// the whole portal into the function bundle at build time. `includeFiles`
// in the function's package.json isn't needed — the builder picks up files
// present under .vercel/output/functions/index.func/ via nft traces of the
// copied tree... simplest reliable path: place it and let the deployment's
// file tracer see the import target on disk.
import { cp } from 'node:fs/promises'
const FUNC = join(ROOT, '.vercel', 'output', 'functions', 'index.func')
try {
  await mkdir(FUNC, { recursive: true })
  await cp(join(ROOT, 'examples', 'chat-portal'), join(FUNC, 'examples', 'chat-portal'), {
    recursive: true,
    filter: (src) => {
      const rel = src.slice(join(ROOT, 'examples', 'chat-portal').length)
      // skip node_modules (deps resolve from the function's own), .data (ephemeral)
      return !/\/(node_modules|\.data)(\/|$)/.test(rel)
    },
  })
  console.log('build-web: copied examples/chat-portal → function bundle (mounted at /portal)')

  // Vendored pay-kit: `file:` deps install as SYMLINKS, which the Vercel
  // file tracer does not follow — copy real files into the function's
  // node_modules so the portal's '@solana/pay-kit' import resolves at runtime.
  const pkDest = join(FUNC, 'node_modules', '@solana', 'pay-kit')
  await mkdir(dirname(pkDest), { recursive: true })
  await cp(join(ROOT, 'vendor', 'pay-kit'), pkDest, { recursive: true })
  console.log('build-web: vendored @solana/pay-kit → function node_modules')
} catch (err) {
  // The copy runs AFTER vercel's build assembled .vercel/output — if the
  // directory doesn't exist yet (local plain `npm run build:web`), skip.
  console.log(`build-web: portal copy skipped (${err.code ?? err.message})`)
}

// index.html: re-root its two asset references under /dashboard/.
const html = await readFile(join(SRC, 'index.html'), 'utf8')
const rerooted = html
  .replaceAll('href="/styles.css"', 'href="/dashboard/styles.css"')
  .replaceAll('src="/app.js"', 'src="/dashboard/app.js"')
await writeFile(join(OUT, 'index.html'), rerooted)

console.log('build-web: wrote public/dashboard/{index.html,app.js,styles.css} + landing.generated.ts')
